name: Build and Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm run install:clean
        env:
          CI: false
      - uses: papeloto/action-zip@v1
        with:
          files: build/
          recursive: false
          dest: build.zip
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: Latest
          allow_override: true
          files: build.zip
          gzip: false
