name: Build and Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
          uses: thedoctor0/zip-release@master
          with:
            filename: 'scripts.zip'
            path: './scripts'
