name: Build and Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          npm run install:clean
        env:
          CI: false

      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          zip -r build.zip build

      - uses: meeDamian/github-release@2.0
      - name: Create release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: Latest
          allow_override: true
          files: build.zip
          gzip: false
